version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  aws-s3: circleci/aws-s3@1.0.0

executors:
  aws:
    docker:
      - image: circleci/python:3.7-node
  cypress:
    docker:
      - image: cypress/base:11.13.0

commands:
  aws_s3_clean:
    description: Removes all contents from an AWS S3 bucket
    parameters:
      target:
        type: string
    steps:
      - aws-cli/install
      - aws-cli/configure:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION
      - run:
          name: S3 Delete all contents in << parameters.target >>
          command: "aws s3 rm << parameters.target >> --recursive"
  npm_install:
    description: Install npm dependencies
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm ci;
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache # Cypress binary

jobs:
  lint:
    executor: cypress
    steps:
      - npm_install
      - run:
          name: Lint
          command: npm run lint
  test:
    executor: cypress
    steps:
      - npm_install
      - run:
          name: Run unit tests
          command: npm run test
      - run:
          name: Run end-to-end tests
          command: npm run test:e2e

  build:
    executor: cypress
    steps:
      - npm_install
      - run:
          name: Build static files
          command: source .circleci/setup_env.sh && npm run build
      - persist_to_workspace:
          root: /root/project
          paths:
            - build
  deploy:
    parameters:
      bucket:
        type: string
    executor: aws
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws_s3_clean:
          target: s3://<< parameters.bucket >>
      - aws-s3/copy:
          from: /tmp/workspace/build
          to: s3://<< parameters.bucket >>
          arguments: --recursive

workflows:
  deploy:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - feature
                - master
                - dev
      - test:
          filters:
            branches:
              only:
                - feature
                - master
                - dev
      - build:
          filters:
            branches:
              only:
                - master
                - dev
      - deploy:
          requires:
            - lint
            - test
            - build
          bucket: chasemate
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - lint
            - test
            - build
          bucket: chasemate-dev
          filters:
            branches:
              only:
                - dev
